name: Check

on:
  push:
    branches:
      - master
      - radix-master
  pull_request:
    branches:
    # Run on PR against any branch

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rustfmt:
    runs-on: "ubuntu-latest"
    steps:
      - name: Install Rust toolchain
        uses: RDXWorks-actions/toolchain@master
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - uses: RDXWorks-actions/checkout@main

      - name: Fmt
        run: cargo +nightly fmt --all -- --check

  clippy:
    runs-on: "ubuntu-latest"
    steps:
      - name: Install Rust toolchain
        uses: RDXWorks-actions/toolchain@master
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          default: true

      - uses: RDXWorks-actions/checkout@main

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Install Rust toolchain
        uses: RDXWorks-actions/toolchain@master
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: stable
          default: true

      - uses: RDXWorks-actions/checkout@main

      - name: Cargo build
        run: cargo build

      - name: Cargo build (std + ignore_custom_section)
        run: cargo build --all-features

      - name: Cargo build (no_std)
        run: cargo build --no-default-features

      - name: Cargo build (wasm)
        run: cargo build --no-default-features --target wasm32-unknown-unknown

  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Rust toolchain
        uses: RDXWorks-actions/toolchain@master
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: RDXWorks-actions/checkout@main

      - name: Cargo test
        run: cargo test

      - name: Cargo test (std + ignore_custom_section)
        run: cargo test --all-features
